import { StyleSheet } from 'react-native';
import { colors } from '@beakerstack/shared/theme/colors';

export const billingColors = {
  pageBg: colors.pageBg,
  cardBg: colors.cardBg,
  border: colors.border,
  rowDivider: colors.rowDivider,
  textPrimary: colors.textPrimary,
  textMuted: colors.textMuted,
  indigo: colors.brand,
  indigoDark: colors.brandDark,
  errorBg: colors.errorBg,
  errorBorder: colors.errorBorder,
  errorText: colors.errorText,
  infoBg: colors.infoBg,
  infoBorder: colors.infoBorder,
  infoText: colors.infoText,
  warnBg: colors.warnBg,
  warnBorder: colors.warnBorder,
  warnText: colors.warnText,
};

export const billingStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: billingColors.pageBg },
  scrollContent: { padding: 16, paddingBottom: 40 },
  card: {
    backgroundColor: billingColors.cardBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: billingColors.border,
    padding: 16,
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: billingColors.textPrimary,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: billingColors.textPrimary,
    marginBottom: 8,
  },
  body: { fontSize: 14, color: billingColors.textMuted, lineHeight: 20 },
  small: { fontSize: 12, color: billingColors.textMuted, lineHeight: 18 },
  primaryBtn: {
    backgroundColor: billingColors.indigo,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 8,
  },
  primaryBtnText: { color: '#fff', fontWeight: '600', fontSize: 15 },
  secondaryBtn: {
    borderWidth: 1,
    borderColor: billingColors.border,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 8,
  },
  secondaryBtnText: { color: billingColors.textPrimary, fontWeight: '600' },
  link: { color: billingColors.indigo, fontSize: 14, marginTop: 8 },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: billingColors.rowDivider,
  },
  banner: {
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
    marginBottom: 12,
  },
  bannerTitle: { fontWeight: '600', fontSize: 14 },
  bannerBody: { marginTop: 4, fontSize: 14 },
  statTileCard: { marginBottom: 12 },
  statValue: {
    marginTop: 6,
    fontSize: 15,
    fontWeight: '600',
    color: billingColors.textPrimary,
  },
  paymentFailedCard: {
    backgroundColor: billingColors.errorBg,
    borderColor: billingColors.errorBorder,
  },
  sectionBlock: { marginBottom: 8 },
  meterBlock: { marginTop: 12 },
  booleanFeatureLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 8,
  },
  booleanFeatureName: {
    marginLeft: 8,
    color: billingColors.textPrimary,
  },
});
