/* eslint-disable no-console -- build script */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { marked } from 'marked';
import { legal } from '../../../adopter/config/legal.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CONTENT_DIR = join(__dirname, '../../../adopter/content');
const OUTPUT_FILE = join(__dirname, '../src/generated/policies.ts');

function substituteTokens(content: string): string {
  return content
    .replace(/\{\{brandName\}\}/g, legal.brandName)
    .replace(/\{\{brandUrl\}\}/g, legal.brandUrl)
    .replace(/\{\{legalEntityName\}\}/g, legal.legalEntityName)
    .replace(/\{\{contactEmail\}\}/g, legal.contactEmail);
}

async function buildPolicy(filename: string): Promise<string> {
  const raw = readFileSync(join(CONTENT_DIR, filename), 'utf-8');
  const substituted = substituteTokens(raw);
  return await marked(substituted);
}

async function main() {
  mkdirSync(join(__dirname, '../src/generated'), { recursive: true });

  const [termsHtml, privacyHtml, refundsHtml] = await Promise.all([
    buildPolicy('terms.md'),
    buildPolicy('privacy.md'),
    buildPolicy('refunds.md'),
  ]);

  const output = `// Generated by packages/shared/scripts/build-policies.ts — do not edit by hand.
// Run \`npm run build:policies\` in packages/shared to regenerate.

export const POLICIES: Record<PolicyKey, string> = {
  terms: ${JSON.stringify(termsHtml)},
  privacy: ${JSON.stringify(privacyHtml)},
  refunds: ${JSON.stringify(refundsHtml)},
};

export type PolicyKey = 'terms' | 'privacy' | 'refunds';
`;

  writeFileSync(OUTPUT_FILE, output, 'utf-8');
  console.log('✓ Generated packages/shared/src/generated/policies.ts');
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
