/* eslint-disable no-console -- build script */
import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath, pathToFileURL } from 'url';
import { marked } from 'marked';
import { format, resolveConfig } from 'prettier';
import type { Legal } from '../../../adopter/config/legal.ts';
import { sanitizeHelpHtml } from '../src/sanitizeHelpHtml.js';
import type { HelpContent } from '../src/types.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '../../..');
const PRETTIER_CONFIG_ANCHOR = join(REPO_ROOT, 'packages/help/package.json');
const CONTENT_FILE = join(__dirname, '../../../adopter/content/help.md');
const OUTPUT_FILE = join(__dirname, '../src/generated/help.ts');

function substituteTokens(content: string, legal: Legal): string {
  return content
    .replace(/\{\{brandName\}\}/g, legal.brandName)
    .replace(/\{\{brandUrl\}\}/g, legal.brandUrl)
    .replace(/\{\{legalEntityName\}\}/g, legal.legalEntityName)
    .replace(/\{\{contactEmail\}\}/g, legal.contactEmail)
    .replace(/\{\{contactPhone\}\}/g, legal.contactPhone)
    .replace(/\{\{mailingAddress\}\}/g, legal.mailingAddress);
}

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

export function lineAt(lines: readonly string[], index: number): string {
  return lines.at(index) ?? '';
}

function stripMarkdownLinks(text: string): string {
  let out = '';
  let i = 0;
  while (i < text.length) {
    if (text[i] === '[') {
      const labelStart = i + 1;
      const bracketEnd = text.indexOf(']', labelStart);
      if (bracketEnd !== -1 && text[bracketEnd + 1] === '(') {
        const urlEnd = text.indexOf(')', bracketEnd + 2);
        if (urlEnd !== -1) {
          out += text.slice(labelStart, bracketEnd);
          i = urlEnd + 1;
          continue;
        }
      }
    }
    out += text[i];
    i += 1;
  }
  return out;
}

export function markdownToPlainText(markdown: string): string {
  return stripMarkdownLinks(markdown)
    .replace(/^[ \t]*[-*+] /gm, '')
    .replace(/[#*_`>~]/g, '')
    .replace(/\n+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export function parseHelpMarkdown(raw: string, legal: Legal): HelpContent {
  const substituted = substituteTokens(raw.trim(), legal);
  const lines = substituted.split('\n');

  let title = 'Help & Support';
  let subtitle = '';
  const sectionBlocks: Array<{ title: string; body: string }> = [];

  let i = 0;
  while (i < lines.length) {
    const rawLine = lineAt(lines, i);
    if (rawLine.startsWith('## ')) {
      break;
    }
    const line = rawLine.trim();
    if (line.startsWith('# ')) {
      title = line.slice(2).trim();
    } else if (line.length > 0 && !subtitle) {
      subtitle = line;
    }
    i++;
  }

  while (i < lines.length && lineAt(lines, i).startsWith('## ')) {
    const sectionTitle = lineAt(lines, i).slice(3).trim();
    i++;
    const bodyLines: string[] = [];
    while (i < lines.length) {
      const rawBodyLine = lineAt(lines, i);
      if (rawBodyLine.startsWith('## ')) {
        break;
      }
      bodyLines.push(rawBodyLine);
      i++;
    }
    const body = bodyLines.join('\n').trim();
    sectionBlocks.push({ title: sectionTitle, body });
  }

  return {
    title,
    subtitle,
    sections: sectionBlocks.map(({ title: sectionTitle, body }) => ({
      id: slugify(sectionTitle),
      title: sectionTitle,
      html: sanitizeHelpHtml(marked.parse(body) as string),
      searchText: markdownToPlainText(body),
    })),
  };
}

export async function formatGeneratedFile(outputFile: string): Promise<void> {
  const source = readFileSync(outputFile, 'utf-8');
  const config = await resolveConfig(PRETTIER_CONFIG_ANCHOR);
  const formatted = await format(source, {
    ...config,
    filepath: outputFile,
  });
  writeFileSync(outputFile, formatted, 'utf-8');
}

export async function buildHelpContent(
  legal?: Legal,
  contentFile: string = CONTENT_FILE,
  outputFile: string = OUTPUT_FILE
): Promise<void> {
  mkdirSync(dirname(outputFile), { recursive: true });

  let resolvedLegal = legal;
  if (!resolvedLegal) {
    const legalModule = await import(
      pathToFileURL(join(__dirname, '../../../adopter/config/legal.ts')).href
    );
    resolvedLegal = legalModule.legal as Legal;
  }

  const raw = readFileSync(contentFile, 'utf-8');
  const help = parseHelpMarkdown(raw, resolvedLegal);

  const output = `// Generated by packages/help/scripts/build-help.ts — do not edit by hand.
// Run \`npm run build:help\` in packages/help to regenerate.

import type { HelpContent } from '../types.js';

export const HELP: HelpContent = ${JSON.stringify(help, null, 2)};
`;

  writeFileSync(outputFile, output, 'utf-8');
  await formatGeneratedFile(outputFile);
  console.log('✓ Generated packages/help/src/generated/help.ts');
}

export function shouldRunMain(
  argv1: string | undefined = process.argv[1],
  moduleUrl: string = import.meta.url
): boolean {
  if (!argv1) return false;
  return pathToFileURL(argv1).href === moduleUrl;
}

export async function main(
  contentFile: string = CONTENT_FILE,
  outputFile: string = OUTPUT_FILE
): Promise<void> {
  await buildHelpContent(undefined, contentFile, outputFile);
}

export async function runCli(
  runMain: () => Promise<void> = main
): Promise<void> {
  try {
    await runMain();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
}

export function runIfMainModule(
  checkMain: () => boolean = shouldRunMain,
  cli: () => Promise<void> = runCli
): void {
  if (checkMain()) {
    void cli();
  }
}

runIfMainModule();
